/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as MinersRouteImport } from './routes/miners'
import { Route as MaintainersRouteImport } from './routes/maintainers'
import { Route as InstallRouteImport } from './routes/install'
import { Route as FairnessRouteImport } from './routes/fairness'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstallIndexRouteImport } from './routes/install.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ApiIndexRouteImport } from './routes/api.index'
import { Route as InstallPermissionsRouteImport } from './routes/install.permissions'
import { Route as DocsFumadocsSpikeApiReferenceRouteImport } from './routes/docs.fumadocs-spike-api-reference'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as AppWorkbenchRouteImport } from './routes/app.workbench'
import { Route as AppRunsRouteImport } from './routes/app.runs'
import { Route as AppReposRouteImport } from './routes/app.repos'
import { Route as AppPlaygroundRouteImport } from './routes/app.playground'
import { Route as AppOwnerRouteImport } from './routes/app.owner'
import { Route as AppOperatorRouteImport } from './routes/app.operator'
import { Route as AppMinerRouteImport } from './routes/app.miner'
import { Route as AppMaintainerRouteImport } from './routes/app.maintainer'
import { Route as AppDigestRouteImport } from './routes/app.digest'
import { Route as AppConfigGeneratorRouteImport } from './routes/app.config-generator'
import { Route as AppCommandsRouteImport } from './routes/app.commands'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as ApiOpRouteImport } from './routes/api.$op'
import { Route as ReposOwnerRepoQualityRouteImport } from './routes/repos.$owner.$repo.quality'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const MinersRoute = MinersRouteImport.update({
  id: '/miners',
  path: '/miners',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintainersRoute = MaintainersRouteImport.update({
  id: '/maintainers',
  path: '/maintainers',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const FairnessRoute = FairnessRouteImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallIndexRoute = InstallIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstallRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiRoute,
} as any)
const InstallPermissionsRoute = InstallPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => InstallRoute,
} as any)
const DocsFumadocsSpikeApiReferenceRoute =
  DocsFumadocsSpikeApiReferenceRouteImport.update({
    id: '/fumadocs-spike-api-reference',
    path: '/fumadocs-spike-api-reference',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const AppWorkbenchRoute = AppWorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppReposRoute = AppReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundRoute = AppPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerRoute = AppOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorRoute = AppOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AppRoute,
} as any)
const AppMinerRoute = AppMinerRouteImport.update({
  id: '/miner',
  path: '/miner',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintainerRoute = AppMaintainerRouteImport.update({
  id: '/maintainer',
  path: '/maintainer',
  getParentRoute: () => AppRoute,
} as any)
const AppDigestRoute = AppDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigGeneratorRoute = AppConfigGeneratorRouteImport.update({
  id: '/config-generator',
  path: '/config-generator',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandsRoute = AppCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiOpRoute = ApiOpRouteImport.update({
  id: '/$op',
  path: '/$op',
  getParentRoute: () => ApiRoute,
} as any)
const ReposOwnerRepoQualityRoute = ReposOwnerRepoQualityRouteImport.update({
  id: '/repos/$owner/$repo/quality',
  path: '/repos/$owner/$repo/quality',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api': typeof ApiRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/extension': typeof ExtensionRoute
  '/fairness': typeof FairnessRoute
  '/install': typeof InstallRouteWithChildren
  '/maintainers': typeof MaintainersRoute
  '/miners': typeof MinersRoute
  '/roadmap': typeof RoadmapRoute
  '/api/$op': typeof ApiOpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/commands': typeof AppCommandsRoute
  '/app/config-generator': typeof AppConfigGeneratorRoute
  '/app/digest': typeof AppDigestRoute
  '/app/maintainer': typeof AppMaintainerRoute
  '/app/miner': typeof AppMinerRoute
  '/app/operator': typeof AppOperatorRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/playground': typeof AppPlaygroundRoute
  '/app/repos': typeof AppReposRoute
  '/app/runs': typeof AppRunsRoute
  '/app/workbench': typeof AppWorkbenchRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/fumadocs-spike-api-reference': typeof DocsFumadocsSpikeApiReferenceRoute
  '/install/permissions': typeof InstallPermissionsRoute
  '/api/': typeof ApiIndexRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/install/': typeof InstallIndexRoute
  '/repos/$owner/$repo/quality': typeof ReposOwnerRepoQualityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/changelog': typeof ChangelogRoute
  '/extension': typeof ExtensionRoute
  '/fairness': typeof FairnessRoute
  '/maintainers': typeof MaintainersRoute
  '/miners': typeof MinersRoute
  '/roadmap': typeof RoadmapRoute
  '/api/$op': typeof ApiOpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/commands': typeof AppCommandsRoute
  '/app/config-generator': typeof AppConfigGeneratorRoute
  '/app/digest': typeof AppDigestRoute
  '/app/maintainer': typeof AppMaintainerRoute
  '/app/miner': typeof AppMinerRoute
  '/app/operator': typeof AppOperatorRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/playground': typeof AppPlaygroundRoute
  '/app/repos': typeof AppReposRoute
  '/app/runs': typeof AppRunsRoute
  '/app/workbench': typeof AppWorkbenchRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/fumadocs-spike-api-reference': typeof DocsFumadocsSpikeApiReferenceRoute
  '/install/permissions': typeof InstallPermissionsRoute
  '/api': typeof ApiIndexRoute
  '/app': typeof AppIndexRoute
  '/docs': typeof DocsIndexRoute
  '/install': typeof InstallIndexRoute
  '/repos/$owner/$repo/quality': typeof ReposOwnerRepoQualityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api': typeof ApiRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/extension': typeof ExtensionRoute
  '/fairness': typeof FairnessRoute
  '/install': typeof InstallRouteWithChildren
  '/maintainers': typeof MaintainersRoute
  '/miners': typeof MinersRoute
  '/roadmap': typeof RoadmapRoute
  '/api/$op': typeof ApiOpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/commands': typeof AppCommandsRoute
  '/app/config-generator': typeof AppConfigGeneratorRoute
  '/app/digest': typeof AppDigestRoute
  '/app/maintainer': typeof AppMaintainerRoute
  '/app/miner': typeof AppMinerRoute
  '/app/operator': typeof AppOperatorRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/playground': typeof AppPlaygroundRoute
  '/app/repos': typeof AppReposRoute
  '/app/runs': typeof AppRunsRoute
  '/app/workbench': typeof AppWorkbenchRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/fumadocs-spike-api-reference': typeof DocsFumadocsSpikeApiReferenceRoute
  '/install/permissions': typeof InstallPermissionsRoute
  '/api/': typeof ApiIndexRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/install/': typeof InstallIndexRoute
  '/repos/$owner/$repo/quality': typeof ReposOwnerRepoQualityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/api'
    | '/app'
    | '/changelog'
    | '/docs'
    | '/extension'
    | '/fairness'
    | '/install'
    | '/maintainers'
    | '/miners'
    | '/roadmap'
    | '/api/$op'
    | '/app/analytics'
    | '/app/audit'
    | '/app/commands'
    | '/app/config-generator'
    | '/app/digest'
    | '/app/maintainer'
    | '/app/miner'
    | '/app/operator'
    | '/app/owner'
    | '/app/playground'
    | '/app/repos'
    | '/app/runs'
    | '/app/workbench'
    | '/docs/$slug'
    | '/docs/fumadocs-spike-api-reference'
    | '/install/permissions'
    | '/api/'
    | '/app/'
    | '/docs/'
    | '/install/'
    | '/repos/$owner/$repo/quality'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/changelog'
    | '/extension'
    | '/fairness'
    | '/maintainers'
    | '/miners'
    | '/roadmap'
    | '/api/$op'
    | '/app/analytics'
    | '/app/audit'
    | '/app/commands'
    | '/app/config-generator'
    | '/app/digest'
    | '/app/maintainer'
    | '/app/miner'
    | '/app/operator'
    | '/app/owner'
    | '/app/playground'
    | '/app/repos'
    | '/app/runs'
    | '/app/workbench'
    | '/docs/$slug'
    | '/docs/fumadocs-spike-api-reference'
    | '/install/permissions'
    | '/api'
    | '/app'
    | '/docs'
    | '/install'
    | '/repos/$owner/$repo/quality'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/api'
    | '/app'
    | '/changelog'
    | '/docs'
    | '/extension'
    | '/fairness'
    | '/install'
    | '/maintainers'
    | '/miners'
    | '/roadmap'
    | '/api/$op'
    | '/app/analytics'
    | '/app/audit'
    | '/app/commands'
    | '/app/config-generator'
    | '/app/digest'
    | '/app/maintainer'
    | '/app/miner'
    | '/app/operator'
    | '/app/owner'
    | '/app/playground'
    | '/app/repos'
    | '/app/runs'
    | '/app/workbench'
    | '/docs/$slug'
    | '/docs/fumadocs-spike-api-reference'
    | '/install/permissions'
    | '/api/'
    | '/app/'
    | '/docs/'
    | '/install/'
    | '/repos/$owner/$repo/quality'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ApiRoute: typeof ApiRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRouteWithChildren
  ExtensionRoute: typeof ExtensionRoute
  FairnessRoute: typeof FairnessRoute
  InstallRoute: typeof InstallRouteWithChildren
  MaintainersRoute: typeof MaintainersRoute
  MinersRoute: typeof MinersRoute
  RoadmapRoute: typeof RoadmapRoute
  ReposOwnerRepoQualityRoute: typeof ReposOwnerRepoQualityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miners': {
      id: '/miners'
      path: '/miners'
      fullPath: '/miners'
      preLoaderRoute: typeof MinersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintainers': {
      id: '/maintainers'
      path: '/maintainers'
      fullPath: '/maintainers'
      preLoaderRoute: typeof MaintainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairness': {
      id: '/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof FairnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/': {
      id: '/install/'
      path: '/'
      fullPath: '/install/'
      preLoaderRoute: typeof InstallIndexRouteImport
      parentRoute: typeof InstallRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/': {
      id: '/api/'
      path: '/'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof ApiRoute
    }
    '/install/permissions': {
      id: '/install/permissions'
      path: '/permissions'
      fullPath: '/install/permissions'
      preLoaderRoute: typeof InstallPermissionsRouteImport
      parentRoute: typeof InstallRoute
    }
    '/docs/fumadocs-spike-api-reference': {
      id: '/docs/fumadocs-spike-api-reference'
      path: '/fumadocs-spike-api-reference'
      fullPath: '/docs/fumadocs-spike-api-reference'
      preLoaderRoute: typeof DocsFumadocsSpikeApiReferenceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/app/workbench': {
      id: '/app/workbench'
      path: '/workbench'
      fullPath: '/app/workbench'
      preLoaderRoute: typeof AppWorkbenchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/runs': {
      id: '/app/runs'
      path: '/runs'
      fullPath: '/app/runs'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/repos': {
      id: '/app/repos'
      path: '/repos'
      fullPath: '/app/repos'
      preLoaderRoute: typeof AppReposRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/playground': {
      id: '/app/playground'
      path: '/playground'
      fullPath: '/app/playground'
      preLoaderRoute: typeof AppPlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/owner': {
      id: '/app/owner'
      path: '/owner'
      fullPath: '/app/owner'
      preLoaderRoute: typeof AppOwnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operator': {
      id: '/app/operator'
      path: '/operator'
      fullPath: '/app/operator'
      preLoaderRoute: typeof AppOperatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/miner': {
      id: '/app/miner'
      path: '/miner'
      fullPath: '/app/miner'
      preLoaderRoute: typeof AppMinerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/maintainer': {
      id: '/app/maintainer'
      path: '/maintainer'
      fullPath: '/app/maintainer'
      preLoaderRoute: typeof AppMaintainerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/digest': {
      id: '/app/digest'
      path: '/digest'
      fullPath: '/app/digest'
      preLoaderRoute: typeof AppDigestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config-generator': {
      id: '/app/config-generator'
      path: '/config-generator'
      fullPath: '/app/config-generator'
      preLoaderRoute: typeof AppConfigGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commands': {
      id: '/app/commands'
      path: '/commands'
      fullPath: '/app/commands'
      preLoaderRoute: typeof AppCommandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$op': {
      id: '/api/$op'
      path: '/$op'
      fullPath: '/api/$op'
      preLoaderRoute: typeof ApiOpRouteImport
      parentRoute: typeof ApiRoute
    }
    '/repos/$owner/$repo/quality': {
      id: '/repos/$owner/$repo/quality'
      path: '/repos/$owner/$repo/quality'
      fullPath: '/repos/$owner/$repo/quality'
      preLoaderRoute: typeof ReposOwnerRepoQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiRouteChildren {
  ApiOpRoute: typeof ApiOpRoute
  ApiIndexRoute: typeof ApiIndexRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiOpRoute: ApiOpRoute,
  ApiIndexRoute: ApiIndexRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCommandsRoute: typeof AppCommandsRoute
  AppConfigGeneratorRoute: typeof AppConfigGeneratorRoute
  AppDigestRoute: typeof AppDigestRoute
  AppMaintainerRoute: typeof AppMaintainerRoute
  AppMinerRoute: typeof AppMinerRoute
  AppOperatorRoute: typeof AppOperatorRoute
  AppOwnerRoute: typeof AppOwnerRoute
  AppPlaygroundRoute: typeof AppPlaygroundRoute
  AppReposRoute: typeof AppReposRoute
  AppRunsRoute: typeof AppRunsRoute
  AppWorkbenchRoute: typeof AppWorkbenchRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCommandsRoute: AppCommandsRoute,
  AppConfigGeneratorRoute: AppConfigGeneratorRoute,
  AppDigestRoute: AppDigestRoute,
  AppMaintainerRoute: AppMaintainerRoute,
  AppMinerRoute: AppMinerRoute,
  AppOperatorRoute: AppOperatorRoute,
  AppOwnerRoute: AppOwnerRoute,
  AppPlaygroundRoute: AppPlaygroundRoute,
  AppReposRoute: AppReposRoute,
  AppRunsRoute: AppRunsRoute,
  AppWorkbenchRoute: AppWorkbenchRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsFumadocsSpikeApiReferenceRoute: typeof DocsFumadocsSpikeApiReferenceRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsFumadocsSpikeApiReferenceRoute: DocsFumadocsSpikeApiReferenceRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface InstallRouteChildren {
  InstallPermissionsRoute: typeof InstallPermissionsRoute
  InstallIndexRoute: typeof InstallIndexRoute
}

const InstallRouteChildren: InstallRouteChildren = {
  InstallPermissionsRoute: InstallPermissionsRoute,
  InstallIndexRoute: InstallIndexRoute,
}

const InstallRouteWithChildren =
  InstallRoute._addFileChildren(InstallRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ApiRoute: ApiRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRouteWithChildren,
  ExtensionRoute: ExtensionRoute,
  FairnessRoute: FairnessRoute,
  InstallRoute: InstallRouteWithChildren,
  MaintainersRoute: MaintainersRoute,
  MinersRoute: MinersRoute,
  RoadmapRoute: RoadmapRoute,
  ReposOwnerRepoQualityRoute: ReposOwnerRepoQualityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
