import { describe, expect, it } from "vitest";
import { REPO_DOC_MARKER_END, REPO_DOC_MARKER_START, renderRepoDocContent } from "../../src/review/repo-doc-render";
import type { RepoProfile, RepoProfileFileNamingStyle, RepoProfileTestFileConvention } from "../../src/review/repo-profile";
import { REPO_PROFILE_SCHEMA_VERSION } from "../../src/review/repo-profile";
import { LOOPOVER_SITE_URL } from "../../src/github/footer";

function presentProfile(overrides: Partial<Extract<RepoProfile, { present: true }>> = {}): RepoProfile {
  return {
    version: REPO_PROFILE_SCHEMA_VERSION,
    present: true,
    repoFullName: "owner/widgets",
    generatedAt: "2026-07-04T00:00:00.000Z",
    architecture: { indexedFileCount: 42, topLevelDirectories: [{ path: "src", fileCount: 30 }, { path: ".", fileCount: 12 }] },
    conventions: { fileNamingStyle: "kebab-case", testFileConvention: "dot-test-suffix" },
    commands: { packageManager: "npm", buildCommands: ["build"], testCommands: ["test"], lintCommands: ["lint"] },
    contributionWorkflow: { gatePublishesCheck: true, linkedIssuePolicy: "preferred", requireLinkedIssue: false, linkedIssueGateMode: "advisory", ciWorkflowFiles: [".github/workflows/ci.yml"] },
    ...overrides,
  };
}

describe("renderRepoDocContent (#3000)", () => {
  it("renders null for an absent profile, never a placeholder document", () => {
    const profile: RepoProfile = { version: REPO_PROFILE_SCHEMA_VERSION, present: false, repoFullName: "owner/widgets", generatedAt: "now", reason: "no RAG index configured or populated for this repo yet" };
    expect(renderRepoDocContent(profile, LOOPOVER_SITE_URL)).toBeNull();
  });

  it("renders the marker, architecture, conventions, commands, and workflow sections for a full profile", () => {
    const content = renderRepoDocContent(presentProfile(), LOOPOVER_SITE_URL);
    expect(content).not.toBeNull();
    expect(content!.startsWith(REPO_DOC_MARKER_START)).toBe(true);
    expect(content!.trimEnd().endsWith(REPO_DOC_MARKER_END)).toBe(true);
    expect(content).toContain("# AGENTS.md");
    expect(content).toContain("42 indexed source files across 2 top-level directories");
    expect(content).toContain("- `src` -- 30 files");
    expect(content).toContain("- `.` -- 12 files");
    expect(content).toContain("File naming: kebab-case (`my-file.ts`)");
    expect(content).toContain("Test files: `*.test.*` files");
    expect(content).toContain("Package manager: npm");
    expect(content).toContain("Build: `npm run build`");
    expect(content).toContain("Test: `npm run test`");
    expect(content).toContain("Lint: `npm run lint`");
    expect(content).toContain("CI publishes a required check: yes");
    expect(content).toContain("Linked-issue policy: preferred");
    expect(content).toContain("Requires a linked issue: no");
    expect(content).toContain("- `.github/workflows/ci.yml`");
    expect(content).toContain("Generated by LoopOver from this repository's own indexed code.");
    expect(content).toContain(`This file is generated by [LoopOver](${LOOPOVER_SITE_URL})`);
  });

  // #4613: a self-hoster's own domain (resolved by the caller from PUBLIC_SITE_ORIGIN) replaces
  // LOOPOVER_SITE_URL in the attribution link -- the SAME (profile, siteUrl) pair still renders
  // identically on repeat calls, preserving the purity/determinism the diff-aware refresh depends on.
  it("#4613: renders the caller-provided siteUrl in the attribution link instead of LOOPOVER_SITE_URL", () => {
    const selfHostedUrl = "https://loopover.example.org";
    const content = renderRepoDocContent(presentProfile(), selfHostedUrl);
    expect(content).toContain(`This file is generated by [LoopOver](${selfHostedUrl})`);
    expect(content).not.toContain(LOOPOVER_SITE_URL);
  });

  it("#4613: renders byte-identical output for the same (profile, siteUrl) pair on repeat calls", () => {
    const selfHostedUrl = "https://loopover.example.org";
    const a = renderRepoDocContent(presentProfile(), selfHostedUrl);
    const b = renderRepoDocContent(presentProfile(), selfHostedUrl);
    expect(a).toEqual(b);
  });

  it("renders byte-identical output for the same profile facts regardless of generatedAt, so refresh's no-change check is meaningful", () => {
    const a = renderRepoDocContent(presentProfile({ generatedAt: "2026-01-01T00:00:00.000Z" }), LOOPOVER_SITE_URL);
    const b = renderRepoDocContent(presentProfile({ generatedAt: "2026-12-31T23:59:59.000Z" }), LOOPOVER_SITE_URL);
    expect(a).toEqual(b);
  });

  it("uses singular wording for exactly one indexed file and one top-level directory", () => {
    const content = renderRepoDocContent(presentProfile({ architecture: { indexedFileCount: 1, topLevelDirectories: [{ path: "src", fileCount: 1 }] } }), LOOPOVER_SITE_URL);
    expect(content).toContain("1 indexed source file across 1 top-level directory:");
    expect(content).toContain("- `src` -- 1 file");
  });

  it("caps the rendered top-level directory list and reports how many were omitted", () => {
    const topLevelDirectories = Array.from({ length: 15 }, (_, i) => ({ path: `dir${i}`, fileCount: 15 - i }));
    const content = renderRepoDocContent(presentProfile({ architecture: { indexedFileCount: 200, topLevelDirectories } }), LOOPOVER_SITE_URL);
    expect(content).toContain("- `dir11` -- 4 files");
    expect(content).not.toContain("`dir12`");
    expect(content).toContain("- (3 more, not shown)");
  });

  it("degrades to 'none detected' for empty build/test/lint command lists", () => {
    const content = renderRepoDocContent(presentProfile({ commands: { packageManager: "npm", buildCommands: [], testCommands: [], lintCommands: [] } }), LOOPOVER_SITE_URL);
    expect(content).toContain("- Build: none detected");
    expect(content).toContain("- Test: none detected");
    expect(content).toContain("- Lint: none detected");
  });

  it("falls back to npm as the runner prefix and 'not detected' label when no package manager is known", () => {
    const content = renderRepoDocContent(presentProfile({ commands: { packageManager: null, buildCommands: ["build"], testCommands: [], lintCommands: [] } }), LOOPOVER_SITE_URL);
    expect(content).toContain("Package manager: not detected");
    expect(content).toContain("- Build: `npm run build`");
  });

  it("renders each non-npm package manager as its own run-command prefix", () => {
    for (const packageManager of ["yarn", "pnpm", "bun"] as const) {
      const content = renderRepoDocContent(presentProfile({ commands: { packageManager, buildCommands: ["build"], testCommands: [], lintCommands: [] } }), LOOPOVER_SITE_URL);
      expect(content).toContain(`Package manager: ${packageManager}`);
      expect(content).toContain(`- Build: \`${packageManager} run build\``);
    }
  });

  it("lists multiple commands for the same category as a comma-separated set", () => {
    const content = renderRepoDocContent(presentProfile({ commands: { packageManager: "npm", buildCommands: [], testCommands: ["test", "test:watch"], lintCommands: [] } }), LOOPOVER_SITE_URL);
    expect(content).toContain("- Test: `npm run test`, `npm run test:watch`");
  });

  it("renders 'none indexed' when no CI workflow files were found", () => {
    const content = renderRepoDocContent(presentProfile({ contributionWorkflow: { gatePublishesCheck: false, linkedIssuePolicy: "optional", requireLinkedIssue: false, linkedIssueGateMode: "advisory", ciWorkflowFiles: [] } }), LOOPOVER_SITE_URL);
    expect(content).toContain("CI publishes a required check: no");
    expect(content).toContain("Requires a linked issue: no");
    expect(content).toContain("- none indexed");
  });

  it("renders 'yes' for requireLinkedIssue only when linkedIssueGateMode is 'block'", () => {
    const content = renderRepoDocContent(presentProfile({ contributionWorkflow: { gatePublishesCheck: true, linkedIssuePolicy: "required", requireLinkedIssue: true, linkedIssueGateMode: "block", ciWorkflowFiles: [] } }), LOOPOVER_SITE_URL);
    expect(content).toContain("Requires a linked issue: yes");
  });

  it("does not claim a linked issue is required when requireLinkedIssue is on but linkedIssueGateMode is the advisory default (#5287)", () => {
    // requireLinkedIssue alone only surfaces an advisory finding -- it never blocks on its own, so the
    // generated doc must not claim "yes" unless linkedIssueGateMode is actually "block".
    const content = renderRepoDocContent(presentProfile({ contributionWorkflow: { gatePublishesCheck: true, linkedIssuePolicy: "required", requireLinkedIssue: true, linkedIssueGateMode: "advisory", ciWorkflowFiles: [] } }), LOOPOVER_SITE_URL);
    expect(content).toContain("Requires a linked issue: no");
    expect(content).not.toContain("Requires a linked issue: yes");
  });

  const namingStyles: Array<[RepoProfileFileNamingStyle, string]> = [
    ["kebab-case", "kebab-case (`my-file.ts`)"],
    ["camelCase", "camelCase (`myFile.ts`)"],
    ["snake_case", "snake_case (`my_file.ts`)"],
    ["PascalCase", "PascalCase (`MyFile.ts`)"],
    ["mixed", "mixed -- no single dominant style detected"],
    ["unknown", "not detected"],
  ];
  it.each(namingStyles)("renders the file-naming label for %s", (style, label) => {
    const content = renderRepoDocContent(presentProfile({ conventions: { fileNamingStyle: style, testFileConvention: "none-detected" } }), LOOPOVER_SITE_URL);
    expect(content).toContain(`File naming: ${label}`);
  });

  const testConventions: Array<[RepoProfileTestFileConvention, string]> = [
    ["dot-test-suffix", "`*.test.*` files"],
    ["dot-spec-suffix", "`*.spec.*` files"],
    ["tests-directory", "a `tests/`/`__tests__/` directory"],
    ["none-detected", "not detected"],
  ];
  it.each(testConventions)("renders the test-file-convention label for %s", (convention, label) => {
    const content = renderRepoDocContent(presentProfile({ conventions: { fileNamingStyle: "unknown", testFileConvention: convention } }), LOOPOVER_SITE_URL);
    expect(content).toContain(`Test files: ${label}`);
  });
});
